SET session_replication_role = replica;

TRUNCATE TABLE roles RESTART IDENTITY CASCADE;
TRUNCATE TABLE permissions RESTART IDENTITY CASCADE;
TRUNCATE TABLE roles_permissions RESTART IDENTITY CASCADE;
TRUNCATE TABLE categories RESTART IDENTITY CASCADE;
TRUNCATE TABLE categories_treepaths RESTART IDENTITY CASCADE;
TRUNCATE TABLE products RESTART IDENTITY CASCADE;
TRUNCATE TABLE products_categories RESTART IDENTITY CASCADE;
TRUNCATE TABLE products_prices RESTART IDENTITY CASCADE;
TRUNCATE TABLE addresses RESTART IDENTITY CASCADE;
TRUNCATE TABLE stores RESTART IDENTITY CASCADE;
TRUNCATE TABLE stores_renovations RESTART IDENTITY CASCADE;
TRUNCATE TABLE employees RESTART IDENTITY CASCADE;
TRUNCATE TABLE employees_roles RESTART IDENTITY CASCADE;
TRUNCATE TABLE customers RESTART IDENTITY CASCADE;
TRUNCATE TABLE sales RESTART IDENTITY CASCADE;
TRUNCATE TABLE products_sales RESTART IDENTITY CASCADE;
TRUNCATE TABLE returns RESTART IDENTITY CASCADE;
TRUNCATE TABLE returns_products RESTART IDENTITY CASCADE;
TRUNCATE TABLE inventories_transactions RESTART IDENTITY CASCADE;

SET session_replication_role = origin;